import * as Types from "../actions/types";

// Some of the properties are redundant.
const initialUserObj = {
  "gender":[
    {label: 'Male',
    value: 'Male',
    color: '#5a5858'},
    {label: 'Female',
    value: 'Female',
    color: '#5a5858'}
  ],
  "servings":[
    { type:'scotch',
      label: 'large - 60ml',
    value: 'large',
    id:'0',
    code:'60',
    color: '#5a5858'},
    { type:'scotch',
      label: 'small - 45ml',
    value: 'small',
    id:'1',
    code:'45',
    color: '#5a5858'},
    { type:'whiskey',
      label: 'large - 60ml',
    value: 'large',
    id:'2',
    code:'60',
    color: '#5a5858'},
    { type:'whiskey',
      label: 'small - 45ml',
    value: 'small',
    id:'3',
    code:'45',
    color: '#5a5858'},
    { type:'beer',
      label: 'small - 355ml',
    value: 'small',
    id:'4',
    code:'355',
    color: '#5a5858'},
    {type:'beer',
      label: 'large - 650ml',
    value: 'large',
    id:'5',
    code:'650',
    color: '#5a5858'},
    {type:'beer',
    label: 'can - 355ml',
    value: 'can',
    id:'6',
    code:'355',
    color: '#5a5858'},
    {type:'wine',
    label: 'glass - 150ml',
    value: 'glass',
    id:'7',
    code:'150',
    color: '#5a5858'}
  ],
    "alcohols":[
              {label: 'Whiskey',
              value: 'Whiskey',
              color: '#5a5858',
            id:0},
              {label: 'Beer',
              value: 'Beer',
              color: '#5a5858',
              id:1},
              {label: 'Scotch',
              value: 'Scotch',
              color: '#5a5858',
              id:2},
              {label: 'Wine',
              value: 'Wine',
              color: '#5a5858',
            id:3}
            ],
    "brands":[
            { type:'Whiskey',
              label: 'Ben Nevis 10Y',
              value: 'Ben Nevis 10Y',
              alcohol:'62.4',              
              color: '#5a5858'},

              { type:'Beer',
              label: 'Abita Amber',
              value: 'Abita Amber',
              alcohol:'4.5',              
              color: '#5a5858'},

              { type:'Beer',
              label: 'Abita Golden',
              value: 'Abita Golden',
              alcohol:'4.2',              
              color: '#5a5858'},

              { type:'Beer',
              label: 'Abita Jockamo IPA',
              value: 'Abita Jockamo IPA',
              alcohol:'6.5',              
              color: '#5a5858'},


              { type:'Beer',
              label: 'Abita Light',
              value: 'Abita Light',
              alcohol:'4.0',              
              color: '#5a5858'},              

              {type:'Whiskey',label: 'Balmenach 30Y',
              value: 'Balmenach 30Y',              
              alcohol:'51.5',
              color: '#5a5858'},
              {type:'Whiskey',label: 'Belvenie 12Y',
              value: 'Belvenie 12Y',
              alcohol:'40',
              color: '#5a5858'},
              {type:'Whiskey',label: 'lagavulin 16Y',
              value: 'lagavulin 16Y',
              alcohol:'40',
              color: '#5a5858'},
              { type:'Wine',
              label: 'Moscato d’Asti',
              value: 'Moscato d’Asti',
              alcohol:'5.5',
              color: '#5a5858'},
              {type:'Wine',label: 'Pinot grigio',
              value: 'Pinot grigio',
              alcohol:'5.5',
              color: '#5a5858'},
              {type:'Wine',label: 'Bordeaux',
              value: 'Bordeaux',
              alcohol:'5.5',
              color: '#5a5858'},
              {type:'Wine',label: 'Champagne',
              value: 'Champagne',
              alcohol:'5.5',
              color: '#5a5858'},   
              {type:'Scotch',label: 'Balmenach 30Y',
              value: 'Balmenach 30Y',              
              alcohol:'51.5',
              color: '#5a5858'},
              {type:'Scotch',label: 'Belvenie 12Y',
              value: 'Belvenie 12Y',
              alcohol:'40',
              color: '#5a5858'},
              {type:'Scotch',label: 'lagavulin 16Y',
              value: 'lagavulin 16Y',
              alcohol:'40',
              color: '#5a5858'},           
            ],   
    "locations":[
      {label: 'Michigan',
    value: '48334',
    color: '#5a5858'},
    {label: 'Ohio',
    value: '43082',
    color: '#5a5858'},
    {label: 'New Jersey',
    value: '08540',
    color: '#5a5858'}
  ] 
  };

  export default (state = initialUserObj, action) => {
    switch (action.type) {
      case Types.GET_ALCOHOL:
        return { ...state }; 
      case Types.GET_SERVING:
        return  { ...state };           
      default:
        return state;
    }
  }