export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SERVER_RESPONSE_ERROR = 'LOGIN_USER_SERVER_RESPONSE_ERROR';
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS = 'LOGIN_USER_SERVER_RESPONSE_SUCCESS';

export const ADD_DRINKS = 'ADD_DRINKS';
export const GET_DRINKS_LIST = 'GET_DRINKS_LIST';
export const ADD_DRINKS_SERVER_RESPONSE_ERROR = 'ADD_DRINKS_SERVER_RESPONSE_ERROR';
export const ADD_DRINKS_SERVER_RESPONSE_SUCCESS = 'ADD_DRINKS_SERVER_RESPONSE_SUCCESS';

export const ADD_INPUTS = 'ADD_INPUTS';
export const ADD_INPUTS_SERVER_RESPONSE_ERROR = 'ADD_INPUTS_SERVER_RESPONSE_ERROR';
export const ADD_INPUTS_SERVER_RESPONSE_SUCCESS = 'ADD_INPUTS_SERVER_RESPONSE_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SERVER_RESPONSE_ERROR= 'FORGOT_PASSWORD_SERVER_RESPONSE_ERROR';
export const FORGOT_PASSWORD_SERVER_RESPONSE_SUCCESS = 'FORGOT_PASSWORD_SERVER_RESPONSE_SUCCESS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SERVER_REQ = 'REGISTER_USER_SERVER_REQ';
export const REGISTER_USER_SERVER_RESPONSE_ERROR = 'REGISTER_USER_SERVER_RESPONSE_ERROR';
export const REGISTER_USER_SERVER_RESPONSE_SUCCESS = 'REGISTER_USER_SERVER_RESPONSE_SUCCESS';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SERVER_RESPONSE_ERROR = 'SIGN_UP_SERVER_RESPONSE_ERROR';
export const SIGN_UP_SERVER_RESPONSE_SUCCESS = 'SIGN_UP_SERVER_RESPONSE_SUCCESS';

export const GET_ALCOHOL = 'GET_ALCOHOL';
export const GET_SERVING = 'GET_SERVING';

export const INPUT_SUBMIT = 'INPUT_SUBMIT';


export const INSERT_NEW_USER = 'INSERT_NEW_USER';
export const INSERT_NEW_USER_SUCCESS = 'INSERT_NEW_USER_SUCCESS';
export const INSERT_NEW_USER_ERROR = 'INSERT_NEW_USER_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SERVER_RESPONSE_ERROR = 'GET_USER_SERVER_RESPONSE_ERROR';
export const GET_USER_SERVER_RESPONSE_SUCCESS = 'GET_USER_SERVER_RESPONSE_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SERVER_RESPONSE_ERROR = 'UPDATE_USER_SERVER_RESPONSE_ERROR';
export const UPDATE_USER_SERVER_RESPONSE_SUCCESS = 'UPDATE_USER_SERVER_RESPONSE_SUCCESS';


export const UPDATE_INPUTS = 'UPDATE_INPUTS';
export const UPDATE_INPUTS_SERVER_RESPONSE_ERROR = 'UPDATE_INPUTS_SERVER_RESPONSE_ERROR';
export const UPDATE_INPUTS_SERVER_RESPONSE_SUCCESS = 'UPDATE_INPUTS_SERVER_RESPONSE_SUCCESS';

export const CLEAR_BAC = 'CLEAR_BAC';
export const CLEAR_BAC_SERVER_RESPONSE_ERROR = 'CLEAR_BAC_SERVER_RESPONSE_ERROR';
export const CLEAR_BAC_SERVER_RESPONSE_SUCCESS = 'CLEAR_BAC_SERVER_RESPONSE_SUCCESS';

export const UPDATED_BAC = 'UPDATED_BAC';
export const UPDATED_BAC_SERVER_RESPONSE_ERROR = 'UPDATED_BAC_SERVER_RESPONSE_ERROR';
export const UPDATED_BAC_SERVER_RESPONSE_SUCCESS = 'UPDATED_BAC_SERVER_RESPONSE_SUCCESS';

export const UPDATE_DRINK = 'UPDATE_DRINK';
export const UPDATE_DRINK_SERVER_RESPONSE_ERROR = 'UPDATE_DRINK_SERVER_RESPONSE_ERROR';
export const UPDATE_DRINK_SERVER_RESPONSE_SUCCESS = 'UPDATE_DRINK_SERVER_RESPONSE_SUCCESS';